version: '3'
services:
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
